name: Coverage

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest hypothesis coverage pytest-coverage
          python -m pip install .

      - name: Run Tests
        run: |
          pytest tests -v --cov-config .coveragerc --cov=src/soundevent/ -l --tb=short --maxfail=1 tests/
          coverage xml
          coverage html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
