name: Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          python -m pip install pytest hypothesis ruff mypy black html5lib
          python -m pip install .
      - name: Check format is correct
        run: |
          black --check src
          black --check tests
      - name: Make sure types are consistent
        run: mypy --ignore-missing-imports src
      - name: Lint with ruff
        run: ruff src
      - name: Test with pytest
        run: pytest tests
